# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='chatmessage',
            index_together=set([('thread', 'created_at')]),
        ),
    ]
